application:
  settings_version: '1.3'
  group_name: 'CDE'
  group_owner: 'jvlarble@gmail.com'
  group_host: 'dev.kodethon.com'
    
# Will be exposed to frontend
environments:
  python: 
    2.7.9: 'jvlythical/python:2.7.9'
    3.0.0: 'jvlythical/python:2.7.9'
  c: 'jvlythical/c_cpp:5.4.0'
  go: 'jvlythical/go:1.3.3'
  java: 'jvlythical/java:1.8.0'
  javascript : 'jvlythical/javascript:node-5.6.0'
  lisp: 'jvlythical/lisp:common-2.49'
  php: 'jvlythical/php:5.6.24'
  prolog: 'jvlythical/prolog:gnu-1.4.4'
  r: 'jvlythical/r-lang:3.2.3'
  ruby: 'jvlythical/ruby:2.2.3'
  rust: 'jvlythical/rust:1.11.0'
  swift: 'jvlythical/swift:2.2'
  test: 
    - 'postgres'
    - 'jvlythical/python:2.7.9'
  
  
  #test: 
  #  - postgres
  #  - 'jvlythical/python:2.7.9'

#ruby: 
#    2.1.3: 'jvlythical/ruby:2.1.3'
#    2.2.3: 'jvlythical/ruby:2.2.3'

global_shell_settings:
  Run:
    Display: '__SHELL'
  Exec: 
    Display: '__SHELL'
    Command: 
      - '*'

_custom_shell_settings:
  python:
    Run:
      Display: '__TERM'
      Command: ['ls']
    Exec:
      Display: '__TERM'
      Command: 
        - 'rails *'
        - 'sudo rails *'
  ruby:
    Exec:
      Display: '__TERM'
      Command: 
        - 'rails *'
        - 'sudo rails *'

global_container_settings: 
  Plugins:
    - CDE
    - Terminal
    - Kodrive
  #Env:
  #  - 'VIRTUAL_HOST=:container_short_name.:host'
  #  - 'LETSENCRYPT_HOST=:container_short_name.:host'
  #  - 'LETSENCRYPT_EMAIL=jvlarble@gmail.com'
  User: 'kodethon'
  WorkingDir: '/home/kodethon'
  Flags:
    - OpenStdin
    - Tty
  Cmd: ['sh', '-c', 'sudo service ssh start; /bin/bash'] 
  HostConfig:
    Flags:
      - PublishAllPorts
    BlkioDeviceWriteBps:
      - Path: '/dev/sda'
        Rate: 10485760
    BlkioDeviceReadBps: 
      - Path: '/dev/sda'
        Rate: 10485760
    CpuPeriod: 100000
    CpuQuota: 200000
    Memory: 536870912
    KernelMemory: 104857600
 
custom_container_settings:
  c_cpp:
    SecurityOpt:
      - 'seccomp:unconfined'
  ruby:
    Env:
      - 'TEST=1'
  example:
    Cmd: ['/bin/sh']  
    Volumes:
      - name: 'secret'
        mountPath: 'config/database.yml'
    PortBindings:
      - externalPort: 80
        internalPort: 80
    Env:
      - "TEST1=1"
      - "TEST2=2"
    SecurityOpt:
      - 'apparmor:unconfined'
  test:
    HostConfig:
      Binds: 
        - '/root:/root'
      
